config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'

  devise_for :golfers, :controllers => { omniauth_callbacks: 'omniauth/omniauth_callbacks', registrations: 'registrations' }

  resources :golfers, only: [:index, :show, :destroy] do
    resources :rounds, only: [:show, :new, :create, :edit, :update, :destroy]
  end

  resources :golf_courses do
    resources :rounds, only: [:index, :create]
    resources :golf_course_comments, only: [:create, :edit, :update, :destroy]
  end

end

app/models/golf_course.rb
require 'memoist'
class GolfCourse < ApplicationRecord
  extend Memoist
  after_commit :unmemoize_all

  validates_presence_of :name, :description, :holes, :total_par, :course_slope, :course_rating
  validates_uniqueness_of :name
  validates :holes, numericality: { equal_to: 18 }
  validates :total_par, numericality: { greater_than: 62 }
  validates :course_rating, numericality: { greater_than: 60 }
  validates :course_slope, numericality: { greater_than: 99 }

  has_many :rounds
  has_many :golfers, through: :rounds
  has_many :golf_course_tags
  has_many :tags, through: :golf_course_tags
  has_many :golf_course_comments

  def golf_course_comments_attributes=(golf_course_comments_attributes)
    golf_course_comments_attributes.values.each do |golf_course_comments_attribute|
      if golf_course_comments_attribute[:content].present?
        self.golf_course_comments.build(content: golf_course_comments_attribute[:content], golfer_id:  golf_course_comments_attribute[:golfer_id])
      end
    end
  end

  def tags_attributes=(tag_attributes)
    tag_attributes.values.each do |tag_attribute|
      if tag_attribute[:name].present?
        tag = Tag.find_or_create_by(name: tag_attribute[:name])
        if !self.tags.include?(tag)
          self.golf_course_tags.build(tag: tag)
        end
      end
    end
  end

  def course_lowest_round
    self.rounds.order(:score).first
  end


  memoize :course_lowest_round

  def self.lowest_course_slope
    @lowest_course_slope ||= self.order(:course_slope).first
  end

  def self.highest_course_slope
    @highest_course_slope ||= self.order(:course_slope).last
  end

  def self.unmemoize_class_methods_variables
    @lowest_course_slope = nil
    @highest_course_slope = nil
  end

end

app/controllers/golf_courses_controller.rb
class GolfCoursesController < ApplicationController

  before_action :set_golf_course, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user
  after_action :unmemoize_golf_course_variables, only: [:create, :update, :destroy]

  def index
    @golf_courses = GolfCourse.all

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @golf_courses.to_json(only: [:name, :course_slope])}
    end
  end

  def show
    @round = Round.new
    @golf_course_comment = GolfCourseComment.new
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @golf_course }
    end
  end

  def new
    @golf_course = GolfCourse.new
  end

  def create
    @golf_course = GolfCourse.new(golf_course_params)
    if @golf_course.save
      redirect_to @golf_course, { notice: 'golf course created successfully.' }
    else
      render 'golf_courses/new'
    end
  end

  def edit
  end

  def update
    if @golf_course.update(golf_course_params)
      redirect_to @golf_course, { notice: 'golf course updated successfully.' }
    else
      render 'golf_courses/edit'
    end
  end

  def destroy
    authenticate_admin
    Round.where(golf_course_id: @golf_course.id).destroy_all
    GolfCourseComment.where(golf_course_id: @golf_course.id).destroy_all
    GolfCourseTag.where(golf_course_id: @golf_course.id).destroy_all
    @golf_course.destroy
    redirect_to golf_courses_path, { notice: 'golf course deleted!' }
  end

  private

  def set_golf_course
    @golf_course = GolfCourse.find(params[:id])
  end

  def golf_course_params
    params.require(:golf_course).permit(:name, :description, :holes, :total_par, :course_slope,
      :course_rating, tag_ids: [], tags_attributes: [:name], golf_course_comments_attributes: [:content, :golfer_id])
  end

  def unmemoize_golf_course_variables
    GolfCourse.unmemoize_class_methods_variables
    Golfer.unmemoize_class_methods_variables
    Round.unmemoize_class_methods_variables
  end

end

app/helpers/golf_courses_helper.rb
module GolfCoursesHelper
end

app/views/golf_courses/_form.html.erb
<% if golf_course.errors.any? %>
  <div id="error_explanation">
    <h4><%= pluralize(golf_course.errors.count, 'error') %>
    prohibited this golf course from being saved:</h4>

    <ul>
      <% golf_course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for golf_course do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :holes %>
  <%= f.number_field :holes, value: 18 %><br>

  <%= f.label :total_par %>
  <%= f.number_field :total_par %><br>

  <%= f.label :course_rating %>
  <%= f.number_field :course_rating, class: :text_field, :step => 0.1 %><br>

  <%= f.label :course_slope %>
  <%= f.number_field :course_slope %><br><br>

  <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name do |tag| %>
    <%= tag.label(class:"label-checkbox") {tag.check_box + tag.text } %>
  <% end %><br>

  <%= f.fields_for :tags, golf_course.tags.build do |tag_builder| %>
    <%= tag_builder.label 'Add Tag' %>
    <%= tag_builder.text_field :name %>
  <% end %><br>

  <%= f.fields_for :tags, golf_course.tags.build do |tag_builder| %>
    <%= tag_builder.label 'Add Tag' %>
    <%= tag_builder.text_field :name %>
  <% end %><br><br>

  <%= f.fields_for :golf_course_comments, golf_course.golf_course_comments.build do |comment_builder| %>
    <%= comment_builder.hidden_field :golfer_id, value: current_golfer.id %>
    <%= comment_builder.label 'Add Comment' %>
    <%= comment_builder.text_area :content %>
  <% end %><br>

  <p><strong> Description:</strong></p>
  <%= f.text_area :description, { rows: 5, cols: 60} %>

  <br><br>
  <%= f.submit class: "btn-primary" %>
<% end %>

app/views/golf_courses/_golf_course_comment.html.erb
<% if golf_course_comment.errors.any? %>
  <br>
  <div id="error_explanation">
    <h4><%= pluralize(golf_course_comment.errors.count, 'error') %>
    prohibited this golf course from being saved:</h4>

    <ul>
      <% golf_course_comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if params[:action] == "edit" %>
  <br>
  <h4>Update Comment</h4>
<% end %>

<%= form_for([golf_course, golf_course_comment], html: {class: "gc-post-comment", "data-id" => golf_course.id }) do |f| %>
  <%= f.text_area :content %><br>
  <%= f.hidden_field :golfer_id, value: current_golfer.id %>
  <%= f.hidden_field :golf_course_id, value: golf_course.id %>
  <%= f.submit "Post Comment for #{golf_course.name}",
  id: "post-comment", class: "btn-primary post-comment", data: { disable_with: false } %>
<% end %>

<div id="comment-error"></div>

app/views/golf_courses/_golf_course_round.html.erb
<%= form_for([current_golfer, round], html: {class: "gc-post-round", "data-id" => golf_course.id }) do |f| %>
  <%= f.label :score %>
  <%= f.number_field :score %>
  <%= f.hidden_field :golfer_id, value: current_golfer.id %>
  <%= f.hidden_field :golf_course_id, value: golf_course.id %>
  <%= f.submit "Post new Round at #{golf_course.name}",
  id: "post-round", class: "btn-primary post-round", data: { disable_with: false } %>
<% end %>

<div id="roundBlank"></div><br>

app/views/golf_courses/edit.html.erb
<h1>Edit Golf Course</h1>

<%= render partial: 'form', locals: { golf_course: @golf_course } %>

app/views/golf_courses/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Golf Courses</h1>
<hr><br>
<table style='width: 60%'>
  <thead>
    <tr>
      <th align="left"><strong>Golf Course</strong></th>
      <th align="center"><strong>Holes</strong></th>
      <th align="center"><strong>Total Par</strong></th>
      <th align="center"><strong><%= current_golfer.name %>'s Course Handicap</strong></th>
    </tr>
  </thead>
  <tbody>
    <% @golf_courses.each do |golf_course| %>
      <tr>
        <td><%= link_to golf_course.name, golf_course_path(golf_course) %></td>
        <td align="center"><%= golf_course.holes %></td>
        <td align="center"><%= golf_course.total_par %></td>
        <td align="center"><%= current_golfer.course_handicap(golf_course).round(1) if current_golfer.golfer_index %></td>
      </tr>
    <% end %>
  </tbody>
</table><br>
<hr><br>

<%= button_to 'Create New Golf Course', new_golf_course_path, class: 'btn-primary', method: 'get' %>

app/views/golf_courses/new.html.erb
<h1>Create New Golf Course</h1>

<%= render partial: 'form', locals: { golf_course: @golf_course } %>

app/views/golf_courses/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @golf_course.name %></h1>
<hr>

<% if current_golfer.golfer_index %>
  <h4>Your Course Handicap, <%= current_golfer.name %>: <%= current_golfer.course_handicap(@golf_course).round(1) %></h4><br>
<% end %>

<%= render partial: 'golf_course_round', locals: { round: @round, golf_course: @golf_course } %>
<hr>

<div class="course description">
  <h4>Course Description:</h4>
  <p><%= @golf_course.description %></p>
</div><br>


  <div class='tags-list'>
    <ul>
      <% if @golf_course.tags.present? %>
        <% @golf_course.tags.each do |tag|%>
          <li><%= tag.name %></li>
        <% end %>
      <% end %>
    </ul><br>
  </div>


<div class="course-details">
  <h4>Course Details:</h4>

  <p>Holes: <%= @golf_course.holes %></p>
  <p>Total Par: <%= @golf_course.total_par %></p>
  <p>Course Slope: <%= @golf_course.course_slope %></p>
  <p>Course rating: <%= @golf_course.course_rating %></p>
  <% if @golf_course.rounds.present? %>
    <p>Low Score: <%= @golf_course.course_lowest_round.score %> by <%= @golf_course.course_lowest_round.golfer.name %></p>
  <% end %>
</div><hr><br>
<%= render partial: 'golf_course_comment', locals: { golf_course_comment: @golf_course_comment, golf_course: @golf_course } %>

<div id="golf-course-comments-<%= @golf_course.id %>"class="golf-course-comments">
  <h4>Comments</h4>
  <% @golf_course.golf_course_comments.each do |comment| %>
    <div class="golf-course-comment" id="golf-course-comment-<%= comment.id %>">
      <h7><b><%= comment.golfer.name %></b>  -  <%= comment.created_at_simple %></h7>
      <% if current_golfer.golf_course_comments.include?(comment) %>
        <div class="gc-comment-destroy">
          <button class="gc-comment-destroy-button" id="gc-comment-destroy-button-<%= comment.id %>" data-id="<%= comment.id %>"
          href='/golf_courses/<%= @golf_course.id %>/golf_course_comments/<%= comment.id %>' data-method="delete">X
          </button>
        </div><br>
      <% end %>
      <p class="gc-comment-content" data-id="<%= comment.id %>" data-url="/golf_courses/<%= @golf_course.id %>/golf_course_comments/<%= comment.id %>/edit">
        <%= comment.content %>
      </p>
    </div>
  <% end %>
</div><hr><br>

<div class="buttons-gc-show">
  <ul>
    <li><button class="btn-info show-rounds" data-id="<%= @golf_course.id %>">Show all Rounds</button></li>
    <li><%= button_to('Edit Golf Course', edit_golf_course_path, class: "btn-warning gc-show", method: 'get') %></li>
    <li><%= button_to('Delete Golf Course', golf_course_path(@golf_course), class:"btn-danger gc-show", method: 'delete') if current_golfer.id == 1 %></li>
    <li><button id='filter-rounds' data-id="<%= @golf_course.id %>"</button>Filter</button></li>
  </ul>
</div><br>

<div id="all-rounds-gc-<%= @golf_course.id %>" class="all-rounds-gc">

</div>

<script id="golf-course-rounds-template" type="text/x-handlebars-template" data-id="<%= current_golfer.id %>">
  <hr><br>
  <table style='width: 65%'>
    <thead>
      <tr>
        <th align="left"><strong>Golfer</strong></th>
        <th align="left"><strong>Score</strong></th>
        <th align="left"><strong>Over/Under</strong></th>
        <th align="left"><strong>Date Posted</strong></th>
      </tr>
    </thead>

    <tbody>
      {{#each rounds}}
        <tr>
         <td><a href="/golfers/{{golfer_id}}">{{golfer_name}}</a></td>
          <td>{{score}}</td>
          <td>{{display_from_par}}</td>
          <td>{{created_at_simple}}</td>
        </tr>
      {{/each}}
    </tbody>
  </table>
  <br>
</script>

<script id="gc-show-round-template" type="text/x-handlebars-template" data-id="<%= @golf_course.id %>">
  <hr><br>
  <table style='width: 65%'>
    <thead>
      <tr>
        <th align="left"><strong>Golfer</strong></th>
        <th align="left"><strong>Score</strong></th>
        <th align="left"><strong>Over/Under</strong></th>
        <th align="left"><strong>Date Posted</strong></th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td>{{golfer_name}}</td>
        <td>{{score}}</td>
        <td>{{display_from_par}}</td>
        <td>{{created_at_simple}}</td>
      </tr>
    </tbody>
  </table>
  <br>
</script>

<script id="gc-show-comment-template" type="text/x-handlebars-template" data-id="<%= current_golfer.id %>">
  <div class="golf-course-comment" id="golf-course-comment-{{id}}">
      <h7><b>{{golfer_name}}</b>  -  {{created_at_simple}}</h7>
        <div class="gc-comment-destroy">
          <button class="gc-comment-destroy-button" id="gc-comment-destroy-button-{{id}}" data-id="{{id}}"
          href='/golf_courses/{{golf_course_id}}/golf_course_comments/{{id}}' data-method="delete">X
          </button>
        </div><br>
        <p class="gc-comment-content" data-id="{{id}}" data-url="/golf_courses/{{golf_course_id}}/golf_course_comments/{{id}}/edit">
          {{content}}
        </p>
    </div>
</script>