config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'

  devise_for :golfers, :controllers => { omniauth_callbacks: 'omniauth/omniauth_callbacks', registrations: 'registrations' }

  resources :golfers, only: [:index, :show, :destroy] do
    resources :rounds, only: [:show, :new, :create, :edit, :update, :destroy]
  end

  resources :golf_courses do
    resources :rounds, only: [:index, :create]
    resources :golf_course_comments, only: [:create, :edit, :update, :destroy]
  end

end

app/models/golfer.rb
require 'memoist'
class Golfer < ActiveRecord::Base
  extend Memoist
  after_commit :unmemoize_all
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]

  validates_presence_of :name

  has_many :rounds
  has_many :golf_courses, through: :rounds
  has_many :golf_course_comments


  def name
    self[:name].split.map(&:capitalize).join(' ') if self[:name]
  end

   def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |golfer|
      golfer.email = auth.info.email
      golfer.name = auth.info.name
      golfer.password = Devise.friendly_token[0,20]
    end
  end

  def golfer_round_indexes
    if self.rounds_posted < 20
      # using range [0..-2] excludes only latest round from all calculations
      self.rounds[0..-2].map { |round| round.round_index }
    else
      # using .offset(1) excludes only latest round from all calculations
      recent_twenty = self.rounds.order(created_at: :desc).limit(20).offset(1)
      #sort by the round_index (known as handicap differential and take range of best 10)
      best_ten = recent_twenty.sort_by { |r| r.round_index }[0..9]
      best_ten.map { |round| round.round_index }
    end
  end

  def golfer_index
    # the golfer needs to have at least 2 rounds since the latest round is not used in the calculation for #golfer_round_indexes
    if self.rounds.size > 1
      full_index = (self.golfer_round_indexes.inject { |sum, round_index| sum + round_index }) / self.golfer_round_indexes.count
      index = (full_index * 0.96).round(1)
    end
  end

  def course_handicap(golf_course)
    (self.golfer_index * golf_course.course_slope / 113).round if self.golfer_index
  end

  def rounds_posted
    self.rounds.count
  end

  def course_most_played
    golf_courses_names = self.golf_courses.map { |golf_course| golf_course.name }
    golf_courses_names.max_by { |gc| golf_courses_names.count(gc) }
  end

  memoize :golfer_round_indexes, :golfer_index, :course_handicap, :rounds_posted, :course_most_played

  #class methods

    def self.golfers_count
      @golfers_count ||= Golfer.all.size
    end

    def self.all_with_index
      @@all_with_index ||= self.all.select { |golfer| golfer.golfer_index }
    end

    def self.lowest_index
      @lowest_index ||= all_with_index.min_by(&:golfer_index)
    end

    def self.unmemoize_class_methods_variables
      @golfers_count = nil
      @@all_with_index = nil
      @lowest_index = nil
    end

end

app/controllers/golfers_controller.rb
class GolfersController < ApplicationController

  before_action :authenticate_user
  after_action :unmemoize_golfer_variables, only: [:create, :update, :destroy]

  def index
    @golfers = Golfer.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @golfers }
    end
  end

  def show
    @last_golfer_id = Golfer.last.id
    @first_golfer_id = Golfer.first.id
    @golfer = Golfer.find(params[:id])
    @rounds_desc = @golfer.rounds.order(created_at: :desc)

    respond_to do |format|
      format.html { render :show }
      format.json { render json: @golfer }
    end
  end

  def destroy
    can_delete_profile
    @golfer = Golfer.find(params[:id])
    Round.where(golfer_id: @golfer.id).destroy_all
    GolfCourseComment.where(golfer_id: @golfer.id).destroy_all
    @golfer.destroy
  end

  private

  def can_delete_profile
    redirect_to root_url unless current_golfer.id == params[:id]
  end

  def unmemoize_golfer_variables
    Golfer.unmemoize_class_methods_variables
  end

end

app/helpers/golfers_helper.rb
module GolfersHelper
end

app/views/golfers/index.html.erb
<h1>Golfers</h1>
<hr><br>
<table style='width: 65%'>
  <thead>
    <tr>
      <th align="left"><strong>Name</strong></th>
      <th align="left"><strong>Index</strong></th>
      <th align="center"><strong>Rounds Posted</strong></th>
      <th align="left"><strong>Email</strong></th>

    </tr>
  </thead>

  <tbody>
    <% @golfers.each do |golfer| %>
      <tr>
        <td><%=link_to golfer.name, golfer_path(golfer) %></td>
        <td><%= golfer.golfer_index if golfer.golfer_index %></td>
        <td align="center"><%= golfer.rounds_posted %></td>
        <td><%= golfer.email %></td>
      </tr>
    <% end %>
  </tbody>
</table><br>
<hr>

app/views/golfers/show.html.erb
<div class="golfer-info">
  <p id="notice"><%= notice %></p>

  <h1 id="golfer-profile-<%= current_golfer.id %>">Golfer Profile for <%= @golfer.name %></h1>
  <hr>
  <h4>Email: <%= @golfer.email %></h4>
  <h4>Index: <%= @golfer.golfer_index if @golfer.golfer_index %></h4>
  <h4>Course Most Played: <%= @golfer.course_most_played if @golfer.rounds.any? %></h4>
  <hr><br>

</div><br>

<button class="btn-primary next-golfer" data-id="<%= @golfer.id %>"
  data-last-golfer-id="<%= @last_golfer_id %>" data-first-golfer-id="<%= @first_golfer_id %>">
  Next Golfer
</button><br><br>

<div class="golfer-rounds">

  <%= button_to 'Post New Round', new_golfer_round_path(@golfer), class: 'btn-success', method: 'get' if current_golfer == @golfer %>

  <h3>Rounds Posted</h3>

  <table style='width: 70%'>
    <thead>
      <tr>
        <th><strong>Golf Course</strong></th>
        <th><strong>Score</strong></th>
        <th><strong>Over/Under</strong></th>
        <th><strong>Net Score</strong></th>
        <th><strong>Net O/U</strong></th>
        <th><strong>Post Date</strong></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @rounds_desc.each do |round| %>
        <tr>
          <td><%= link_to round.golf_course.name, golf_course_path(round.golf_course) %></td>
          <td><%= round.score %></td>
          <td><%= round.display_from_par %></td>
          <td><%= round.net_score %></td>
          <td><%= round.display_net_from_par %></td>
          <td><%= round.created_at_simple %></td>
          <td><%= link_to 'edit round', edit_golfer_round_path(@golfer, round) if current_golfer == @golfer %></td>
        </tr>
      <% end %>
    </tbody>
  </table><br>

  <%= button_to "Delete Profile", golfer_path(@golfer), class: "btn-danger", method: 'delete' if current_golfer.id == params[:id].to_i %><br>
  
</div>

<script id ="golfer-template" type="text/x-handlebars-template">
  <p id="notice"></p>

  <h1>Golfer Profile for {{name}}</h1>
  <hr>
  <h4>Email: {{email}}</h4>
  <h4>Index: {{golfer_index}}</h4>
  <h4>Course Most Played: {{course_most_played}}</h4>
  <hr><br>
</script>

<script id="golfer-rounds-template" type="text/x-handlebars-template" data-id="<%= current_golfer.id %>">
  {{#ifPermissionGolfer id}}
  <form class="button_to" method="get" action="/golfers/{{id}}/rounds/new"><input class="btn-success" type="submit" value="Post New Round" /></form>
  {{/ifPermissionGolfer}}

  <h3>Rounds Posted</h3>

  <table style='width: 70%'>
    <thead>
      <tr>
        <th><strong>Golf Course</strong></th>
        <th><strong>Score</strong></th>
        <th><strong>Over/Under</strong></th>
        <th><strong>Net Score</strong></th>
        <th><strong>Net O/U</strong></th>
        <th><strong>Post Date</strong></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      {{#each rounds}}
        <tr>
          <td><a href="/golf_courses/{{golf_course_id}}">{{golf_course_name}}</a></td>
          <td>{{score}}</td>
          <td>{{display_from_par}}</td>
          <td>{{net_score}}</td>
          <td>{{display_net_from_par}}</td>
          <td>{{created_at_simple}}</td>
          {{#ifPermissionGolfer golfer_id}}
          <td><a href="/golfers/{{golfer_id}}/rounds/{{id}}/edit">edit round</td>
          {{/ifPermissionGolfer}}
        </tr>
      {{/each}}
    </tbody>
  </table><br>

  {{#ifPermissionGolfer id}}
  <form class="button_to" method="post" action="/golfers/2">
    <input type="hidden" name="_method" value="delete" />
    <input class="btn-danger" type="submit" value="Delete Profile" />
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  </form><br>
  {{/ifPermissionGolfer}}
</script>