config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'

  devise_for :golfers, :controllers => { omniauth_callbacks: 'omniauth/omniauth_callbacks', registrations: 'registrations' }

  resources :golfers, only: [:index, :show, :destroy] do
    resources :rounds, only: [:show, :new, :create, :edit, :update, :destroy]
  end

  resources :golf_courses do
    resources :rounds, only: [:index, :create]
    resources :golf_course_comments, only: [:create, :edit, :update, :destroy]
  end

end

app/views/layouts/_navbar.html.erb
<!--  navbar -->
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li><%= link_to "Your Profile, #{current_golfer.name}", golfer_path(current_golfer) %></li>
          <li><%= link_to "Post new Round", new_golfer_round_path(current_golfer) %></li>
          <li><%= link_to "Golf Courses", golf_courses_path %></li>
          <li><%= link_to "Golfers", golfers_path %></li>
          <li><%= link_to "Log Out", destroy_golfer_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_golfer_registration_path%></li>
          <li><%= link_to "Log in", new_golfer_session_path%></li>
          <li><%= link_to "Sign in with Facebook", golfer_facebook_omniauth_authorize_url %></li>
          <li><%= link_to "Sign in with Google", golfer_google_oauth2_omniauth_authorize_url %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Golf Handicapper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"></link>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">

    <%= render '/layouts/navbar' %>

    <div class="spacer">
    </div>

    <div class="container"  role="main">

      <%= yield %>

    </div>

  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Golf Handicapper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"></link>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Covered+By+Your+Grace" />
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <div class="home-spacer"></div>

    <%= render '/layouts/navbar' %>

    <%= yield %>

  </body>
</html>